name: Build and Release AutoGitUploader

on:
  push:
    tags:
      - "v*"  # Triggers when you push a tag like v1.0
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y g++ libcurl4-openssl-dev nlohmann-json3-dev

      - name: Install Dependencies (Windows)
        if: runner.os == 'Windows'
        run: |
          choco install mingw --version=12.2.0 -y
          echo "C:\ProgramData\chocolatey\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8

      - name: Compile (Linux)
        if: runner.os == 'Linux'
        run: g++ -std=c++17 -o AutoGitUploader AutoGitUploader.cpp -lcurl -lstdc++fs

      - name: Compile (Windows)
        if: runner.os == 'Windows'
        run: |
          g++ -std=c++17 -I"C:/curl/include" -I"$env:GITHUB_WORKSPACE/include" `
          -L"C:/curl/lib" AutoGitUploader.cpp -o AutoGitUploader.exe `
          -lcurl -lssl -lcrypto -lz -lws2_32

      - name: Upload Linux Binary
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v4
        with:
          name: AutoGitUploader-linux
          path: AutoGitUploader

      - name: Upload Windows Binary
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: AutoGitUploader-windows
          path: AutoGitUploader.exe

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')  # Ensures release only runs when a tag is pushed
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Linux Binary
        uses: actions/download-artifact@v4
        with:
          name: AutoGitUploader-linux
          path: .

      - name: Download Windows Binary
        uses: actions/download-artifact@v4
        with:
          name: AutoGitUploader-windows
          path: .

      - name: Publish Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            AutoGitUploader
            AutoGitUploader.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GB_TOKEN }}
