name: Build and Release AutoGitUploader

on:
  push:
    tags:
      - "v*"  # Triggers when you push a tag like v1.0
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y g++ libcurl4-openssl-dev nlohmann-json3-dev

      - name: Install Dependencies (Windows)
        if: runner.os == 'Windows'
        run: |
          choco install mingw --version=12.2.0 -y
          echo "C:\ProgramData\chocolatey\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8

      - name: Download and Extract cURL (Windows)
        if: runner.os == 'Windows'
        run: |
          Invoke-WebRequest -Uri "https://curl.se/windows/dl-8.12.1_3/curl-8.12.1_3-win64-mingw.zip" -OutFile "curl.zip"
          Expand-Archive -Path "curl.zip" -DestinationPath "C:/"
          Rename-Item -Path "C:/curl-8.12.1_3-win64-mingw" -NewName "C:/curl"
          echo "C:/curl/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8
          echo "CURL_INCLUDE=C:/curl/include" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8
          echo "CURL_LIB=C:/curl/lib" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8

      - name: Debug Paths (Windows)
        if: runner.os == 'Windows'
        run: |
          echo "Checking cURL headers in C:/curl/include:"
          dir C:/curl/include
          echo "Checking cURL library files in C:/curl/lib:"
          dir C:/curl/lib
          echo "CURL_INCLUDE=$env:CURL_INCLUDE"
          echo "CURL_LIB=$env:CURL_LIB"

      - name: Download json.hpp (Windows)
        if: runner.os == 'Windows'
        run: |
          New-Item -ItemType Directory -Path "$env:GITHUB_WORKSPACE/include/nlohmann" -Force
          Invoke-WebRequest -Uri "https://github.com/nlohmann/json/releases/download/v3.11.3/json.hpp" -OutFile "$env:GITHUB_WORKSPACE/include/nlohmann/json.hpp"

      - name: Compile (Linux)
        if: runner.os == 'Linux'
        run: g++ -std=c++17 -o AutoGitUploader AutoGitUploader.cpp -lcurl -lstdc++fs

      - name: Compile (Windows)
        if: runner.os == 'Windows'
        run: |
          g++ -std=c++17 -I"C:/curl/include" -I"$env:GITHUB_WORKSPACE/include" `
          -L"C:/curl/lib" AutoGitUploader.cpp -o AutoGitUploader.exe `
          -lcurl -lssl -lcrypto -lz -lws2_32

      - name: Upload Linux Binary
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v4
        with:
          name: AutoGitUploader-linux
          path: AutoGitUploader

      - name: Upload Windows Binary
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: AutoGitUploader-windows
          path: AutoGitUploader.exe

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Linux Binary
        uses: actions/download-artifact@v4
        with:
          name: AutoGitUploader-linux
          path: .

      - name: Download Windows Binary
        uses: actions/download-artifact@v4
        with:
          name: AutoGitUploader-windows
          path: .

      - name: Publish Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            AutoGitUploader
            AutoGitUploader.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GB_TOKEN }}
